language: objective-c
osx_image: xcode8.2

env:
    global:
        - PROJECT=GLTableCollectionView.xcodeproj
        - SCHEME=GLTableCollectionView
        - SDK=iphonesimulator10.2
        - DESTINATION="platform=iOS Simulator,OS=10.2,name=iPhone 5"

xcode_project: GLTableCollectionView.xcodeproj
xcode_scheme: GLTableCollectionView
before_install:
    - xcodebuild -version
    - xcodebuild -showsdks

script: xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug test
